name: Custom Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
  - attributes: 
      value: |
        ![image](https://user-images.githubusercontent.com/63423081/172671654-cb514b95-a86b-45dc-a91c-19c1d50081d2.png)
  - type: checkboxes
    id: urgency
    attributes:
      label: Use the matrix above to guide in selecting an urgency level
      options:
        - label: Emergency Hot Fix
        - label: High Priority
        - label: Medium Priority
        - label: Low Priority
        - label: "Won't fix"
      validations: 
        required: true
  - type: checkboxes
    id: customer-reported
    attributes:
      label: Did a customer report this?
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true
  - type: checkboxes
    id: environment
    attributes:
      label: Where was this found?
      options:
        - label: Develop
        - label: Nightly
        - label: Staging
        - label: Production
    validations:
      required: true
  - type: checkboxes
    id: quarter
    attributes:
      label: When did you find this bug?
      options:
        - label: Q1
        - label: Q2
        - label: Q3
        - label: Q4
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: "Provide us with the steps to reproduce the behaviour. Screenshots and/or video help!"
      placeholder: | 
        1. Go to ... 
        2. Click on... 
        3. Scroll down to...
        4. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: "Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks."
      render: shell
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "Provide describe the expected behaviour."
      placeholder: |
        1. Go to ... 
        2. Click on... 
        3. Scroll down to... 
        4. No error
    validations:
      required: true
